const { upsertRoute } = require('./database');

// Parse route text to extract origin and destination codes
function parseRoute(routeText) {
    // Split by " - "
    const parts = routeText.split(' - ');
    if (parts.length !== 2) return null;

    const origin = parts[0].trim();
    const destination = parts[1].trim();

    // Find airport codes for these cities
    let originCode = null;
    let destCode = null;

    // Check if it's already a code
    for (const [code, city] of Object.entries(airports)) {
        if (city === origin || origin.includes(code)) {
            originCode = code;
        }
        if (city === destination || destination.includes(code)) {
            destCode = code;
        }
    }

    if (originCode && destCode) {
        return { origin: originCode, destination: destCode };
    }

    return null;
}

// Frontier routes from sitemap (provided by user)
const frontierRoutes = [
    "Aguadilla - Miami, FL",
    "Aguadilla - Orlando, FL",
    "Atlanta, GA - Austin, TX",
    "Atlanta, GA - Baltimore, MD",
    "Atlanta, GA - Boston, MA",
    "Atlanta, GA - Buffalo, NY",
    "Atlanta, GA - Cabo San Lucas",
    "Atlanta, GA - Cancun, MX",
    "Atlanta, GA - Chicago, IL",
    "Atlanta, GA - Cincinnati, OH",
    "Atlanta, GA - Cleveland, OH",
    "Atlanta, GA - Columbus, OH",
    "Atlanta, GA - Dallas, TX",
    "Atlanta, GA - Denver, CO",
    "Atlanta, GA - Detroit, MI",
    "Atlanta, GA - Fort Lauderdale, FL",
    "Atlanta, GA - Fort Myers, FL",
    "Atlanta, GA - Guatemala City",
    "Atlanta, GA - Hartford, CT",
    "Atlanta, GA - Houston, TX",
    "Atlanta, GA - Indianapolis, IN",
    "Atlanta, GA - Islip, NY",
    "Atlanta, GA - Jacksonville, FL",
    "Atlanta, GA - Kansas City, MO",
    "Atlanta, GA - Las Vegas, NV",
    "Atlanta, GA - Los Angeles, CA",
    "Atlanta, GA - Memphis, TN",
    "Atlanta, GA - Miami, FL",
    "Atlanta, GA - Milwaukee, WI",
    "Atlanta, GA - Minneapolis/St. Paul, MN",
    "Atlanta, GA - Montego Bay, Jamaica",
    "Atlanta, GA - Nassau",
    "Atlanta, GA - New Orleans, LA",
    "Atlanta, GA - New York City, NY",
    "Atlanta, GA - Newark, NJ",
    "Atlanta, GA - Norfolk, VA",
    "Atlanta, GA - Oklahoma City, OK",
    "Atlanta, GA - Omaha, NE",
    "Atlanta, GA - Oranjestad, Aruba",
    "Atlanta, GA - Orlando, FL",
    "Atlanta, GA - Philadelphia, PA",
    "Atlanta, GA - Phoenix, AZ",
    "Atlanta, GA - Pittsburgh, PA",
    "Atlanta, GA - Providenciales",
    "Atlanta, GA - Puerto Vallarta, Mexico",
    "Atlanta, GA - Punta Cana, Dominican Republic",
    "Atlanta, GA - Raleigh, NC",
    "Atlanta, GA - Richmond",
    "Atlanta, GA - San Antonio, TX",
    "Atlanta, GA - San Francisco, CA",
    "Atlanta, GA - San Jose, CR",
    "Atlanta, GA - San Juan, PR",
    "Atlanta, GA - San Pedro Sula",
    "Atlanta, GA - San Salvador",
    "Atlanta, GA - St. Louis, MO",
    "Atlanta, GA - St. Maarten",
    "Atlanta, GA - Syracuse, NY",
    "Atlanta, GA - Tampa, FL",
    "Atlanta, GA - Trenton, NJ",
    "Atlanta, GA - Washington, D.C.",
    "Atlanta, GA - West Palm Beach, FL",
    "Austin, TX - Atlanta, GA",
    "Austin, TX - Chicago, IL",
    "Austin, TX - Cincinnati, OH",
    "Austin, TX - Cleveland, OH",
    "Austin, TX - Denver, CO",
    "Austin, TX - Las Vegas, NV",
    "Austin, TX - Miami, FL",
    "Austin, TX - Orlando, FL",
    "Austin, TX - Philadelphia, PA",
    "Austin, TX - Phoenix, AZ",
    "Baltimore, MD - Atlanta, GA",
    "Baltimore, MD - Charlotte, NC",
    "Baltimore, MD - Chicago, IL",
    "Baltimore, MD - Dallas, TX",
    "Baltimore, MD - Denver, CO",
    "Baltimore, MD - Detroit, MI",
    "Baltimore, MD - Miami, FL",
    "Baltimore, MD - Orlando, FL",
    "Baltimore, MD - San Juan, PR",
    "Baltimore, MD - Tampa, FL",
    "Bentonville/Fayetteville, AR - Denver, CO",
    "Boise, ID - Denver, CO",
    "Boston, MA - Atlanta, GA",
    "Boston, MA - Charlotte, NC",
    "Boston, MA - Cincinnati, OH",
    "Boston, MA - Cleveland, OH",
    "Boston, MA - Dallas, TX",
    "Boston, MA - Miami, FL",
    "Boston, MA - Orlando, FL",
    "Boston, MA - Philadelphia, PA",
    "Boston, MA - Raleigh, NC",
    "Boston, MA - San Juan, PR",
    "Boston, MA - Tampa, FL",
    "Bridgetown - San Juan, PR",
    "Buffalo, NY - Atlanta, GA",
    "Buffalo, NY - Charlotte, NC",
    "Buffalo, NY - Denver, CO",
    "Buffalo, NY - Fort Myers, FL",
    "Buffalo, NY - Orlando, FL",
    "Buffalo, NY - Raleigh, NC",
    "Buffalo, NY - Tampa, FL",
    "Burbank - Denver, CO",
    "Burbank - Phoenix, AZ",
    "Burbank - San Francisco, CA",
    "Burlington, VT - Orlando, FL",
    "Burlington, VT - Tampa, FL",
    "Cabo San Lucas - Atlanta, GA",
    "Cabo San Lucas - Denver, CO",
    "Cabo San Lucas - Las Vegas, NV",
    "Cancun, MX - Atlanta, GA",
    "Cancun, MX - Chicago, IL",
    "Cancun, MX - Cincinnati, OH",
    "Cancun, MX - Cleveland, OH",
    "Cancun, MX - Dallas, TX",
    "Cancun, MX - Denver, CO",
    "Cancun, MX - Houston, TX",
    "Cancun, MX - Miami, FL",
    "Cancun, MX - Orlando, FL",
    "Cancun, MX - Philadelphia, PA",
    "Cancun, MX - St. Louis, MO",
    "Cedar Rapids, IA - Denver, CO",
    "Charleston, SC - Dallas, TX",
    "Charleston, SC - Philadelphia, PA",
    "Charlotte, NC - Baltimore, MD",
    "Charlotte, NC - Boston, MA",
    "Charlotte, NC - Buffalo, NY",
    "Charlotte, NC - Chicago, IL",
    "Charlotte, NC - Cleveland, OH",
    "Charlotte, NC - Dallas, TX",
    "Charlotte, NC - Denver, CO",
    "Charlotte, NC - Houston, TX",
    "Charlotte, NC - Miami, FL",
    "Charlotte, NC - New York City, NY",
    "Charlotte, NC - Orlando, FL",
    "Charlotte, NC - Philadelphia, PA",
    "Charlotte, NC - San Juan, PR",
    "Chicago, IL - Atlanta, GA",
    "Chicago, IL - Austin, TX",
    "Chicago, IL - Baltimore, MD",
    "Chicago, IL - Cancun, MX",
    "Chicago, IL - Charlotte, NC",
    "Chicago, IL - Dallas, TX",
    "Chicago, IL - Denver, CO",
    "Chicago, IL - Fort Myers, FL",
    "Chicago, IL - Houston, TX",
    "Chicago, IL - Las Vegas, NV",
    "Chicago, IL - Los Angeles, CA",
    "Chicago, IL - Miami, FL",
    "Chicago, IL - Minneapolis/St. Paul, MN",
    "Chicago, IL - Nashville, TN",
    "Chicago, IL - New York City, NY",
    "Chicago, IL - Newark, NJ",
    "Chicago, IL - Orlando, FL",
    "Chicago, IL - Philadelphia, PA",
    "Chicago, IL - Phoenix, AZ",
    "Chicago, IL - Punta Cana, Dominican Republic",
    "Chicago, IL - Raleigh, NC",
    "Chicago, IL - Salt Lake City, UT",
    "Chicago, IL - Sarasota, FL",
    "Chicago, IL - Tampa, FL",
    "Chicago, IL - West Palm Beach, FL",
    "Cincinnati, OH - Atlanta, GA",
    "Cincinnati, OH - Austin, TX",
    "Cincinnati, OH - Boston, MA",
    "Cincinnati, OH - Cancun, MX",
    "Cincinnati, OH - Dallas, TX",
    "Cincinnati, OH - Denver, CO",
    "Cincinnati, OH - Fort Lauderdale, FL",
    "Cincinnati, OH - Fort Myers, FL",
    "Cincinnati, OH - Houston, TX",
    "Cincinnati, OH - Las Vegas, NV",
    "Cincinnati, OH - Miami, FL",
    "Cincinnati, OH - New York City, NY",
    "Cincinnati, OH - Orlando, FL",
    "Cincinnati, OH - Phoenix, AZ",
    "Cincinnati, OH - Sarasota, FL",
    "Cincinnati, OH - Tampa, FL",
    "Cincinnati, OH - West Palm Beach, FL",
    "Cleveland, OH - Atlanta, GA",
    "Cleveland, OH - Austin, TX",
    "Cleveland, OH - Boston, MA",
    "Cleveland, OH - Cancun, MX",
    "Cleveland, OH - Charlotte, NC",
    "Cleveland, OH - Dallas, TX",
    "Cleveland, OH - Denver, CO",
    "Cleveland, OH - Fort Lauderdale, FL",
    "Cleveland, OH - Fort Myers, FL",
    "Cleveland, OH - Las Vegas, NV",
    "Cleveland, OH - Miami, FL",
    "Cleveland, OH - Myrtle Beach, SC",
    "Cleveland, OH - Nashville, TN",
    "Cleveland, OH - New York City, NY",
    "Cleveland, OH - Orlando, FL",
    "Cleveland, OH - Phoenix, AZ",
    "Cleveland, OH - Punta Cana, Dominican Republic",
    "Cleveland, OH - Raleigh, NC",
    "Cleveland, OH - San Juan, PR",
    "Cleveland, OH - Sarasota, FL",
    "Cleveland, OH - Tampa, FL",
    "Cleveland, OH - West Palm Beach, FL",
    "Columbus, OH - Atlanta, GA",
    "Columbus, OH - Denver, CO",
    "Columbus, OH - Orlando, FL",
    "Corpus Christi - Denver, CO",
    "Dallas, TX - Atlanta, GA",
    "Dallas, TX - Baltimore, MD",
    "Dallas, TX - Boston, MA",
    "Dallas, TX - Cancun, MX",
    "Dallas, TX - Charleston, SC",
    "Dallas, TX - Charlotte, NC",
    "Dallas, TX - Chicago, IL",
    "Dallas, TX - Cincinnati, OH",
    "Dallas, TX - Cleveland, OH",
    "Dallas, TX - Denver, CO",
    "Dallas, TX - Detroit, MI",
    "Dallas, TX - El Paso, TX",
    "Dallas, TX - Guatemala City",
    "Dallas, TX - Houston, TX",
    "Dallas, TX - Indianapolis, IN",
    "Dallas, TX - Jacksonville, FL",
    "Dallas, TX - Las Vegas, NV",
    "Dallas, TX - Los Angeles, CA",
    "Dallas, TX - Miami, FL",
    "Dallas, TX - Minneapolis/St. Paul, MN",
    "Dallas, TX - New York City, NY",
    "Dallas, TX - Norfolk, VA",
    "Dallas, TX - Ontario/LA, CA",
    "Dallas, TX - Orlando, FL",
    "Dallas, TX - Philadelphia, PA",
    "Dallas, TX - Phoenix, AZ",
    "Dallas, TX - Portland, OR",
    "Dallas, TX - Puerto Vallarta, Mexico",
    "Dallas, TX - Raleigh, NC",
    "Dallas, TX - Salt Lake City, UT",
    "Dallas, TX - San Diego, CA",
    "Dallas, TX - San Francisco, CA",
    "Dallas, TX - San Juan, PR",
    "Dallas, TX - San Salvador",
    "Dallas, TX - Seattle, WA",
    "Dallas, TX - St. Louis, MO",
    "Dallas, TX - Tampa, FL",
    "Dallas, TX - Tucson, AZ",
    "Dallas, TX - Vail",
    "Dallas, TX - Washington, D.C.",
    "Denver, CO - Atlanta, GA",
    "Denver, CO - Austin, TX",
    "Denver, CO - Baltimore, MD",
    "Denver, CO - Bentonville/Fayetteville, AR",
    "Denver, CO - Boise, ID",
    "Denver, CO - Buffalo, NY",
    "Denver, CO - Burbank",
    "Denver, CO - Cabo San Lucas",
    "Denver, CO - Cancun, MX",
    "Denver, CO - Cedar Rapids, IA",
    "Denver, CO - Charlotte, NC",
    "Denver, CO - Chicago, IL",
    "Denver, CO - Cincinnati, OH",
    "Denver, CO - Cleveland, OH",
    "Denver, CO - Columbus, OH",
    "Denver, CO - Corpus Christi",
    "Denver, CO - Dallas, TX",
    "Denver, CO - Des Moines, IA",
    "Denver, CO - Detroit, MI",
    "Denver, CO - El Paso, TX",
    "Denver, CO - Fargo, ND",
    "Denver, CO - Fort Myers, FL",
    "Denver, CO - Grand Rapids, MI",
    "Denver, CO - Green Bay, WI",
    "Denver, CO - Houston, TX",
    "Denver, CO - Indianapolis, IN",
    "Denver, CO - Kansas City, MO",
    "Denver, CO - Knoxville, TN",
    "Denver, CO - Las Vegas, NV",
    "Denver, CO - Little Rock, AR",
    "Denver, CO - Los Angeles, CA",
    "Denver, CO - Madison, WI",
    "Denver, CO - Memphis, TN",
    "Denver, CO - Miami, FL",
    "Denver, CO - Milwaukee, WI",
    "Denver, CO - Minneapolis/St. Paul, MN",
    "Denver, CO - Missoula, MT",
    "Denver, CO - Nashville, TN",
    "Denver, CO - New Orleans, LA",
    "Denver, CO - New York City, NY",
    "Denver, CO - Oklahoma City, OK",
    "Denver, CO - Omaha, NE",
    "Denver, CO - Ontario/LA, CA",
    "Denver, CO - Orlando, FL",
    "Denver, CO - Palm Springs, CA",
    "Denver, CO - Pensacola, FL",
    "Denver, CO - Philadelphia, PA",
    "Denver, CO - Phoenix, AZ",
    "Denver, CO - Pittsburgh, PA",
    "Denver, CO - Portland, OR",
    "Denver, CO - Puerto Vallarta, Mexico",
    "Denver, CO - Raleigh, NC",
    "Denver, CO - Reno, NV",
    "Denver, CO - Richmond",
    "Denver, CO - Sacramento, CA",
    "Denver, CO - Salt Lake City, UT",
    "Denver, CO - San Antonio, TX",
    "Denver, CO - San Diego, CA",
    "Denver, CO - San Francisco, CA",
    "Denver, CO - San Jose, CA",
    "Denver, CO - Santa Ana, CA",
    "Denver, CO - Seattle, WA",
    "Denver, CO - Sioux Falls, SD",
    "Denver, CO - Spokane, WA",
    "Denver, CO - St. Louis, MO",
    "Denver, CO - Tampa, FL",
    "Denver, CO - Tucson, AZ",
    "Denver, CO - Tulsa, OK",
    "Denver, CO - Vail",
    "Denver, CO - Washington, D.C.",
    "Des Moines, IA - Denver, CO",
    "Des Moines, IA - Orlando, FL",
    "Detroit, MI - Atlanta, GA",
    "Detroit, MI - Baltimore, MD",
    "Detroit, MI - Dallas, TX",
    "Detroit, MI - Denver, CO",
    "Detroit, MI - Fort Myers, FL",
    "Detroit, MI - Las Vegas, NV",
    "Detroit, MI - Orlando, FL",
    "Detroit, MI - Phoenix, AZ",
    "Detroit, MI - Raleigh, NC",
    "Detroit, MI - Tampa, FL",
    "El Paso, TX - Dallas, TX",
    "El Paso, TX - Denver, CO",
    "El Paso, TX - Las Vegas, NV",
    "Fargo, ND - Denver, CO",
    "Fargo, ND - Orlando, FL",
    "Fort Lauderdale, FL - Atlanta, GA",
    "Fort Lauderdale, FL - Cincinnati, OH",
    "Fort Lauderdale, FL - Cleveland, OH",
    "Fort Lauderdale, FL - Islip, NY",
    "Fort Lauderdale, FL - Philadelphia, PA",
    "Fort Lauderdale, FL - San Juan, PR",
    "Fort Myers, FL - Atlanta, GA",
    "Fort Myers, FL - Buffalo, NY",
    "Fort Myers, FL - Chicago, IL",
    "Fort Myers, FL - Cincinnati, OH",
    "Fort Myers, FL - Cleveland, OH",
    "Fort Myers, FL - Denver, CO",
    "Fort Myers, FL - Detroit, MI",
    "Fort Myers, FL - Grand Rapids, MI",
    "Fort Myers, FL - Islip, NY",
    "Fort Myers, FL - Philadelphia, PA",
    "Fort Myers, FL - Trenton, NJ",
    "Grand Rapids, MI - Denver, CO",
    "Grand Rapids, MI - Fort Myers, FL",
    "Grand Rapids, MI - Orlando, FL",
    "Grand Rapids, MI - Tampa, FL",
    "Green Bay, WI - Denver, CO",
    "Guatemala City - Atlanta, GA",
    "Guatemala City - Dallas, TX",
    "Guatemala City - Miami, FL",
    "Guatemala City - Orlando, FL",
    "Harrisburg, PA - Orlando, FL",
    "Hartford, CT - Atlanta, GA",
    "Hartford, CT - Miami, FL",
    "Hartford, CT - Orlando, FL",
    "Hartford, CT - San Juan, PR",
    "Hartford, CT - Tampa, FL",
    "Houston, TX - Atlanta, GA",
    "Houston, TX - Cancun, MX",
    "Houston, TX - Charlotte, NC",
    "Houston, TX - Chicago, IL",
    "Houston, TX - Cincinnati, OH",
    "Houston, TX - Dallas, TX",
    "Houston, TX - Denver, CO",
    "Houston, TX - Las Vegas, NV",
    "Houston, TX - Los Angeles, CA",
    "Houston, TX - Miami, FL",
    "Houston, TX - Ontario/LA, CA",
    "Houston, TX - Orlando, FL",
    "Houston, TX - Phoenix, AZ",
    "Houston, TX - Raleigh, NC",
    "Houston, TX - Tampa, FL",
    "Indianapolis, IN - Atlanta, GA",
    "Indianapolis, IN - Dallas, TX",
    "Indianapolis, IN - Denver, CO",
    "Indianapolis, IN - Orlando, FL",
    "Indianapolis, IN - Raleigh, NC",
    "Indianapolis, IN - Tampa, FL",
    "Islip, NY - Atlanta, GA",
    "Islip, NY - Fort Lauderdale, FL",
    "Islip, NY - Fort Myers, FL",
    "Islip, NY - Myrtle Beach, SC",
    "Islip, NY - Orlando, FL",
    "Islip, NY - Raleigh, NC",
    "Islip, NY - Tampa, FL",
    "Islip, NY - West Palm Beach, FL",
    "Jacksonville, FL - Atlanta, GA",
    "Jacksonville, FL - Dallas, TX",
    "Jacksonville, FL - Philadelphia, PA",
    "Jacksonville, FL - San Juan, PR",
    "Kansas City, MO - Atlanta, GA",
    "Kansas City, MO - Denver, CO",
    "Kansas City, MO - Tampa, FL",
    "Knoxville, TN - Denver, CO",
    "Las Vegas, NV - Atlanta, GA",
    "Las Vegas, NV - Austin, TX",
    "Las Vegas, NV - Cabo San Lucas",
    "Las Vegas, NV - Chicago, IL",
    "Las Vegas, NV - Cincinnati, OH",
    "Las Vegas, NV - Cleveland, OH",
    "Las Vegas, NV - Dallas, TX",
    "Las Vegas, NV - Denver, CO",
    "Las Vegas, NV - Detroit, MI",
    "Las Vegas, NV - El Paso, TX",
    "Las Vegas, NV - Houston, TX",
    "Las Vegas, NV - Los Angeles, CA",
    "Las Vegas, NV - Miami, FL",
    "Las Vegas, NV - New York City, NY",
    "Las Vegas, NV - Oklahoma City, OK",
    "Las Vegas, NV - Ontario/LA, CA",
    "Las Vegas, NV - Orlando, FL",
    "Las Vegas, NV - Philadelphia, PA",
    "Las Vegas, NV - Phoenix, AZ",
    "Las Vegas, NV - Portland, OR",
    "Las Vegas, NV - Raleigh, NC",
    "Las Vegas, NV - Reno, NV",
    "Las Vegas, NV - Sacramento, CA",
    "Las Vegas, NV - Salt Lake City, UT",
    "Las Vegas, NV - San Antonio, TX",
    "Las Vegas, NV - San Diego, CA",
    "Las Vegas, NV - San Francisco, CA",
    "Las Vegas, NV - San Jose, CA",
    "Las Vegas, NV - Santa Ana, CA",
    "Las Vegas, NV - Seattle, WA",
    "Las Vegas, NV - St. Louis, MO",
    "Las Vegas, NV - Tampa, FL",
    "Las Vegas, NV - Tucson, AZ",
    "Little Rock, AR - Denver, CO",
    "Los Angeles, CA - Atlanta, GA",
    "Los Angeles, CA - Chicago, IL",
    "Los Angeles, CA - Dallas, TX",
    "Los Angeles, CA - Denver, CO",
    "Los Angeles, CA - Houston, TX",
    "Los Angeles, CA - Las Vegas, NV",
    "Los Angeles, CA - New York City, NY",
    "Los Angeles, CA - Orlando, FL",
    "Los Angeles, CA - Philadelphia, PA",
    "Los Angeles, CA - Phoenix, AZ",
    "Los Angeles, CA - Portland, OR",
    "Los Angeles, CA - Sacramento, CA",
    "Los Angeles, CA - Salt Lake City, UT",
    "Los Angeles, CA - San Francisco, CA",
    "Los Angeles, CA - San Jose, CA",
    "Los Angeles, CA - Seattle, WA",
    "Madison, WI - Denver, CO",
    "Madison, WI - Orlando, FL",
    "Memphis, TN - Atlanta, GA",
    "Memphis, TN - Denver, CO",
    "Miami, FL - Aguadilla",
    "Miami, FL - Atlanta, GA",
    "Miami, FL - Austin, TX",
    "Miami, FL - Baltimore, MD",
    "Miami, FL - Boston, MA",
    "Miami, FL - Cancun, MX",
    "Miami, FL - Charlotte, NC",
    "Miami, FL - Chicago, IL",
    "Miami, FL - Cincinnati, OH",
    "Miami, FL - Cleveland, OH",
    "Miami, FL - Dallas, TX",
    "Miami, FL - Denver, CO",
    "Miami, FL - Guatemala City",
    "Miami, FL - Hartford, CT",
    "Miami, FL - Houston, TX",
    "Miami, FL - Las Vegas, NV",
    "Miami, FL - New York City, NY",
    "Miami, FL - Philadelphia, PA",
    "Miami, FL - Punta Cana, Dominican Republic",
    "Miami, FL - Raleigh, NC",
    "Miami, FL - San Juan, PR",
    "Miami, FL - San Pedro Sula",
    "Miami, FL - San Salvador",
    "Miami, FL - Santo Domingo",
    "Miami, FL - Washington, D.C.",
    "Milwaukee, WI - Atlanta, GA",
    "Milwaukee, WI - Denver, CO",
    "Milwaukee, WI - Orlando, FL",
    "Milwaukee, WI - Tampa, FL",
    "Minneapolis/St. Paul, MN - Atlanta, GA",
    "Minneapolis/St. Paul, MN - Chicago, IL",
    "Minneapolis/St. Paul, MN - Dallas, TX",
    "Minneapolis/St. Paul, MN - Denver, CO",
    "Minneapolis/St. Paul, MN - Orlando, FL",
    "Minneapolis/St. Paul, MN - Phoenix, AZ",
    "Missoula, MT - Denver, CO",
    "Montego Bay, Jamaica - Atlanta, GA",
    "Montego Bay, Jamaica - Philadelphia, PA",
    "Myrtle Beach, SC - Cleveland, OH",
    "Myrtle Beach, SC - Islip, NY",
    "Myrtle Beach, SC - Philadelphia, PA",
    "Nashville, TN - Chicago, IL",
    "Nashville, TN - Cleveland, OH",
    "Nashville, TN - Denver, CO",
    "Nashville, TN - Orlando, FL",
    "Nashville, TN - Philadelphia, PA",
    "Nassau - Atlanta, GA",
    "New Orleans, LA - Atlanta, GA",
    "New Orleans, LA - Denver, CO",
    "New Orleans, LA - Orlando, FL",
    "New Orleans, LA - Philadelphia, PA",
    "New York City, NY - Atlanta, GA",
    "New York City, NY - Charlotte, NC",
    "New York City, NY - Chicago, IL",
    "New York City, NY - Cincinnati, OH",
    "New York City, NY - Cleveland, OH",
    "New York City, NY - Dallas, TX",
    "New York City, NY - Denver, CO",
    "New York City, NY - Las Vegas, NV",
    "New York City, NY - Los Angeles, CA",
    "New York City, NY - Miami, FL",
    "New York City, NY - Orlando, FL",
    "New York City, NY - Raleigh, NC",
    "New York City, NY - San Juan, PR",
    "New York City, NY - Tampa, FL",
    "Newark, NJ - Atlanta, GA",
    "Newark, NJ - Chicago, IL",
    "Newark, NJ - San Juan, PR",
    "Norfolk, VA - Atlanta, GA",
    "Norfolk, VA - Dallas, TX",
    "Norfolk, VA - Orlando, FL",
    "Oklahoma City, OK - Atlanta, GA",
    "Oklahoma City, OK - Denver, CO",
    "Oklahoma City, OK - Las Vegas, NV",
    "Oklahoma City, OK - Orlando, FL",
    "Omaha, NE - Atlanta, GA",
    "Omaha, NE - Denver, CO",
    "Omaha, NE - Orlando, FL",
    "Ontario/LA, CA - Dallas, TX",
    "Ontario/LA, CA - Denver, CO",
    "Ontario/LA, CA - Houston, TX",
    "Ontario/LA, CA - Las Vegas, NV",
    "Ontario/LA, CA - Portland, OR",
    "Ontario/LA, CA - Sacramento, CA",
    "Ontario/LA, CA - Salt Lake City, UT",
    "Ontario/LA, CA - San Francisco, CA",
    "Ontario/LA, CA - Seattle, WA",
    "Orlando, FL - Aguadilla",
    "Orlando, FL - Atlanta, GA",
    "Orlando, FL - Austin, TX",
    "Orlando, FL - Baltimore, MD",
    "Orlando, FL - Boston, MA",
    "Orlando, FL - Buffalo, NY",
    "Orlando, FL - Burlington, VT",
    "Orlando, FL - Cancun, MX",
    "Orlando, FL - Charlotte, NC",
    "Orlando, FL - Chicago, IL",
    "Orlando, FL - Cincinnati, OH",
    "Orlando, FL - Cleveland, OH",
    "Orlando, FL - Columbus, OH",
    "Orlando, FL - Dallas, TX",
    "Orlando, FL - Denver, CO",
    "Orlando, FL - Des Moines, IA",
    "Orlando, FL - Detroit, MI",
    "Orlando, FL - Fargo, ND",
    "Orlando, FL - Grand Rapids, MI",
    "Orlando, FL - Guatemala City",
    "Orlando, FL - Harrisburg, PA",
    "Orlando, FL - Hartford, CT",
    "Orlando, FL - Houston, TX",
    "Orlando, FL - Indianapolis, IN",
    "Orlando, FL - Islip, NY",
    "Orlando, FL - Las Vegas, NV",
    "Orlando, FL - Los Angeles, CA",
    "Orlando, FL - Madison, WI",
    "Orlando, FL - Milwaukee, WI",
    "Orlando, FL - Minneapolis/St. Paul, MN",
    "Orlando, FL - Nashville, TN",
    "Orlando, FL - New Orleans, LA",
    "Orlando, FL - New York City, NY",
    "Orlando, FL - Norfolk, VA",
    "Orlando, FL - Oklahoma City, OK",
    "Orlando, FL - Omaha, NE",
    "Orlando, FL - Philadelphia, PA",
    "Orlando, FL - Phoenix, AZ",
    "Orlando, FL - Pittsburgh, PA",
    "Orlando, FL - Ponce",
    "Orlando, FL - Portland, ME",
    "Orlando, FL - Punta Cana, Dominican Republic",
    "Orlando, FL - Raleigh, NC",
    "Orlando, FL - San Antonio, TX",
    "Orlando, FL - San Francisco, CA",
    "Orlando, FL - San Juan, PR",
    "Orlando, FL - San Salvador",
    "Orlando, FL - Santo Domingo",
    "Orlando, FL - St. Louis, MO",
    "Orlando, FL - St. Maarten",
    "Orlando, FL - Syracuse, NY",
    "Orlando, FL - Trenton, NJ",
    "Orlando, FL - Washington, D.C.",
    "Palm Springs, CA - Denver, CO",
    "Palm Springs, CA - San Francisco, CA",
    "Pensacola, FL - Denver, CO",
    "Philadelphia, PA - Atlanta, GA",
    "Philadelphia, PA - Austin, TX",
    "Philadelphia, PA - Boston, MA",
    "Philadelphia, PA - Cancun, MX",
    "Philadelphia, PA - Charleston, SC",
    "Philadelphia, PA - Charlotte, NC",
    "Philadelphia, PA - Chicago, IL",
    "Philadelphia, PA - Dallas, TX",
    "Philadelphia, PA - Denver, CO",
    "Philadelphia, PA - Fort Lauderdale, FL",
    "Philadelphia, PA - Fort Myers, FL",
    "Philadelphia, PA - Jacksonville, FL",
    "Philadelphia, PA - Las Vegas, NV",
    "Philadelphia, PA - Los Angeles, CA",
    "Philadelphia, PA - Miami, FL",
    "Philadelphia, PA - Montego Bay, Jamaica",
    "Philadelphia, PA - Myrtle Beach, SC",
    "Philadelphia, PA - Nashville, TN",
    "Philadelphia, PA - New Orleans, LA",
    "Philadelphia, PA - Orlando, FL",
    "Philadelphia, PA - Pittsburgh, PA",
    "Philadelphia, PA - Punta Cana, Dominican Republic",
    "Philadelphia, PA - Raleigh, NC",
    "Philadelphia, PA - San Juan, PR",
    "Philadelphia, PA - Santo Domingo",
    "Philadelphia, PA - Sarasota, FL",
    "Philadelphia, PA - Savannah, GA",
    "Philadelphia, PA - Tampa, FL",
    "Philadelphia, PA - West Palm Beach, FL",
    "Phoenix, AZ - Atlanta, GA",
    "Phoenix, AZ - Austin, TX",
    "Phoenix, AZ - Burbank",
    "Phoenix, AZ - Chicago, IL",
    "Phoenix, AZ - Cincinnati, OH",
    "Phoenix, AZ - Cleveland, OH",
    "Phoenix, AZ - Dallas, TX",
    "Phoenix, AZ - Denver, CO",
    "Phoenix, AZ - Detroit, MI",
    "Phoenix, AZ - Houston, TX",
    "Phoenix, AZ - Las Vegas, NV",
    "Phoenix, AZ - Los Angeles, CA",
    "Phoenix, AZ - Minneapolis/St. Paul, MN",
    "Phoenix, AZ - Orlando, FL",
    "Phoenix, AZ - Portland, OR",
    "Phoenix, AZ - Reno, NV",
    "Phoenix, AZ - Salt Lake City, UT",
    "Phoenix, AZ - San Antonio, TX",
    "Phoenix, AZ - San Diego, CA",
    "Phoenix, AZ - San Francisco, CA",
    "Phoenix, AZ - San Jose, CA",
    "Phoenix, AZ - Santa Ana, CA",
    "Phoenix, AZ - Seattle, WA",
    "Phoenix, AZ - Spokane, WA",
    "Pittsburgh, PA - Atlanta, GA",
    "Pittsburgh, PA - Denver, CO",
    "Pittsburgh, PA - Orlando, FL",
    "Pittsburgh, PA - Philadelphia, PA",
    "Ponce - Orlando, FL",
    "Port-of-Spain - San Juan, PR",
    "Portland, ME - Orlando, FL",
    "Portland, ME - Tampa, FL",
    "Portland, OR - Dallas, TX",
    "Portland, OR - Denver, CO",
    "Portland, OR - Las Vegas, NV",
    "Portland, OR - Los Angeles, CA",
    "Portland, OR - Ontario/LA, CA",
    "Portland, OR - Phoenix, AZ",
    "Portland, OR - Salt Lake City, UT",
    "Portland, OR - San Francisco, CA",
    "Providenciales - Atlanta, GA",
    "Puerto Vallarta, Mexico - Atlanta, GA",
    "Puerto Vallarta, Mexico - Dallas, TX",
    "Puerto Vallarta, Mexico - Denver, CO",
    "Punta Cana, Dominican Republic - Atlanta, GA",
    "Punta Cana, Dominican Republic - Chicago, IL",
    "Punta Cana, Dominican Republic - Cleveland, OH",
    "Punta Cana, Dominican Republic - Miami, FL",
    "Punta Cana, Dominican Republic - Orlando, FL",
    "Punta Cana, Dominican Republic - Philadelphia, PA",
    "Punta Cana, Dominican Republic - San Juan, PR",
    "Punta Cana, Dominican Republic - St. Louis, MO",
    "Punta Cana, Dominican Republic - Tampa, FL",
    "Raleigh, NC - Atlanta, GA",
    "Raleigh, NC - Boston, MA",
    "Raleigh, NC - Buffalo, NY",
    "Raleigh, NC - Chicago, IL",
    "Raleigh, NC - Cleveland, OH",
    "Raleigh, NC - Dallas, TX",
    "Raleigh, NC - Denver, CO",
    "Raleigh, NC - Detroit, MI",
    "Raleigh, NC - Houston, TX",
    "Raleigh, NC - Indianapolis, IN",
    "Raleigh, NC - Islip, NY",
    "Raleigh, NC - Las Vegas, NV",
    "Raleigh, NC - Miami, FL",
    "Raleigh, NC - New York City, NY",
    "Raleigh, NC - Orlando, FL",
    "Raleigh, NC - Philadelphia, PA",
    "Raleigh, NC - San Juan, PR",
    "Raleigh, NC - Syracuse, NY",
    "Raleigh, NC - Tampa, FL",
    "Reno, NV - Denver, CO",
    "Reno, NV - Las Vegas, NV",
    "Reno, NV - Phoenix, AZ",
    "Richmond - Atlanta, GA",
    "Richmond - Denver, CO",
    "Sacramento, CA - Denver, CO",
    "Sacramento, CA - Las Vegas, NV",
    "Sacramento, CA - Los Angeles, CA",
    "Sacramento, CA - Ontario/LA, CA",
    "Sacramento, CA - San Diego, CA",
    "Saint Croix - San Juan, PR",
    "Salt Lake City, UT - Chicago, IL",
    "Salt Lake City, UT - Dallas, TX",
    "Salt Lake City, UT - Denver, CO",
    "Salt Lake City, UT - Las Vegas, NV",
    "Salt Lake City, UT - Los Angeles, CA",
    "Salt Lake City, UT - Ontario/LA, CA",
    "Salt Lake City, UT - Phoenix, AZ",
    "Salt Lake City, UT - Portland, OR",
    "Salt Lake City, UT - San Francisco, CA",
    "Salt Lake City, UT - Santa Ana, CA",
    "Salt Lake City, UT - Seattle, WA",
    "San Antonio, TX - Atlanta, GA",
    "San Antonio, TX - Denver, CO",
    "San Antonio, TX - Las Vegas, NV",
    "San Antonio, TX - Orlando, FL",
    "San Antonio, TX - Phoenix, AZ",
    "San Diego, CA - Dallas, TX",
    "San Diego, CA - Denver, CO",
    "San Diego, CA - Las Vegas, NV",
    "San Diego, CA - Phoenix, AZ",
    "San Diego, CA - Sacramento, CA",
    "San Diego, CA - San Francisco, CA",
    "San Francisco, CA - Atlanta, GA",
    "San Francisco, CA - Burbank",
    "San Francisco, CA - Dallas, TX",
    "San Francisco, CA - Denver, CO",
    "San Francisco, CA - Las Vegas, NV",
    "San Francisco, CA - Los Angeles, CA",
    "San Francisco, CA - Ontario/LA, CA",
    "San Francisco, CA - Orlando, FL",
    "San Francisco, CA - Palm Springs, CA",
    "San Francisco, CA - Phoenix, AZ",
    "San Francisco, CA - Portland, OR",
    "San Francisco, CA - Salt Lake City, UT",
    "San Francisco, CA - San Diego, CA",
    "San Francisco, CA - Santa Ana, CA",
    "San Francisco, CA - Vail",
    "San Jose, CA - Denver, CO",
    "San Jose, CA - Las Vegas, NV",
    "San Jose, CA - Los Angeles, CA",
    "San Jose, CA - Phoenix, AZ",
    "San Jose, CR - Atlanta, GA",
    "San Juan, PR - Atlanta, GA",
    "San Juan, PR - Baltimore, MD",
    "San Juan, PR - Boston, MA",
    "San Juan, PR - Bridgetown",
    "San Juan, PR - Charlotte, NC",
    "San Juan, PR - Cleveland, OH",
    "San Juan, PR - Dallas, TX",
    "San Juan, PR - Fort Lauderdale, FL",
    "San Juan, PR - Hartford, CT",
    "San Juan, PR - Jacksonville, FL",
    "San Juan, PR - Miami, FL",
    "San Juan, PR - New York City, NY",
    "San Juan, PR - Newark, NJ",
    "San Juan, PR - Orlando, FL",
    "San Juan, PR - Philadelphia, PA",
    "San Juan, PR - Port-of-Spain",
    "San Juan, PR - Puerto Plata",
    "San Juan, PR - Punta Cana, Dominican Republic",
    "San Juan, PR - Raleigh, NC",
    "San Juan, PR - Saint Croix",
    "San Juan, PR - Santiago de los Caballeros",
    "San Juan, PR - Santo Domingo",
    "San Juan, PR - St. John's, Antigua",
    "San Juan, PR - St. Maarten",
    "San Juan, PR - St. Thomas",
    "San Juan, PR - Tampa, FL",
    "San Juan, PR - Washington, D.C.",
    "San Pedro Sula - Miami, FL",
    "San Salvador - Atlanta, GA",
    "San Salvador - Dallas, TX",
    "San Salvador - Miami, FL",
    "San Salvador - Orlando, FL",
    "San Salvador - Washington, D.C.",
    "Santa Ana, CA - Denver, CO",
    "Santa Ana, CA - Las Vegas, NV",
    "Santa Ana, CA - Phoenix, AZ",
    "Santa Ana, CA - Salt Lake City, UT",
    "Santa Ana, CA - San Francisco, CA",
    "Santiago de los Caballeros - San Juan, PR",
    "Santo Domingo - Miami, FL",
    "Santo Domingo - Orlando, FL",
    "Santo Domingo - Philadelphia, PA",
    "Santo Domingo - San Juan, PR",
    "Santo Domingo - Tampa, FL",
    "Sarasota, FL - Chicago, IL",
    "Sarasota, FL - Cincinnati, OH",
    "Sarasota, FL - Cleveland, OH",
    "Sarasota, FL - Philadelphia, PA",
    "Savannah, GA - Philadelphia, PA",
    "Seattle, WA - Dallas, TX",
    "Seattle, WA - Denver, CO",
    "Seattle, WA - Las Vegas, NV",
    "Seattle, WA - Los Angeles, CA",
    "Seattle, WA - Ontario/LA, CA",
    "Seattle, WA - Phoenix, AZ",
    "Seattle, WA - Salt Lake City, UT",
    "Sioux Falls, SD - Denver, CO",
    "Spokane, WA - Denver, CO",
    "Spokane, WA - Phoenix, AZ",
    "St. Louis, MO - Atlanta, GA",
    "St. Louis, MO - Cancun, MX",
    "St. Louis, MO - Dallas, TX",
    "St. Louis, MO - Denver, CO",
    "St. Louis, MO - Las Vegas, NV",
    "St. Louis, MO - Orlando, FL",
    "St. Louis, MO - Punta Cana, Dominican Republic",
    "St. Louis, MO - Tampa, FL",
    "St. Maarten - Atlanta, GA",
    "St. Maarten - Orlando, FL",
    "St. Maarten - San Juan, PR",
    "St. Thomas - San Juan, PR",
    "Syracuse, NY - Atlanta, GA",
    "Syracuse, NY - Orlando, FL",
    "Syracuse, NY - Raleigh, NC",
    "Tampa, FL - Atlanta, GA",
    "Tampa, FL - Baltimore, MD",
    "Tampa, FL - Boston, MA",
    "Tampa, FL - Buffalo, NY",
    "Tampa, FL - Burlington, VT",
    "Tampa, FL - Chicago, IL",
    "Tampa, FL - Cincinnati, OH",
    "Tampa, FL - Cleveland, OH",
    "Tampa, FL - Dallas, TX",
    "Tampa, FL - Denver, CO",
    "Tampa, FL - Detroit, MI",
    "Tampa, FL - Grand Rapids, MI",
    "Tampa, FL - Hartford, CT",
    "Tampa, FL - Houston, TX",
    "Tampa, FL - Indianapolis, IN",
    "Tampa, FL - Islip, NY",
    "Tampa, FL - Kansas City, MO",
    "Tampa, FL - Las Vegas, NV",
    "Tampa, FL - Milwaukee, WI",
    "Tampa, FL - New York City, NY",
    "Tampa, FL - Philadelphia, PA",
    "Tampa, FL - Portland, ME",
    "Tampa, FL - Punta Cana, Dominican Republic",
    "Tampa, FL - Raleigh, NC",
    "Tampa, FL - San Juan, PR",
    "Tampa, FL - Santo Domingo",
    "Tampa, FL - St. Louis, MO",
    "Tampa, FL - Trenton, NJ",
    "Tampa, FL - Washington, D.C.",
    "Trenton, NJ - Atlanta, GA",
    "Trenton, NJ - Fort Myers, FL",
    "Trenton, NJ - Orlando, FL",
    "Trenton, NJ - Tampa, FL",
    "Trenton, NJ - West Palm Beach, FL",
    "Tucson, AZ - Dallas, TX",
    "Tucson, AZ - Denver, CO",
    "Tucson, AZ - Las Vegas, NV",
    "Tulsa, OK - Denver, CO",
    "Vail - Dallas, TX",
    "Vail - Denver, CO",
    "Vail - San Francisco, CA",
    "Washington, D.C. - Atlanta, GA",
    "Washington, D.C. - Dallas, TX",
    "Washington, D.C. - Denver, CO",
    "Washington, D.C. - Miami, FL",
    "Washington, D.C. - Orlando, FL",
    "Washington, D.C. - San Juan, PR",
    "Washington, D.C. - San Salvador",
    "Washington, D.C. - Tampa, FL",
    "West Palm Beach, FL - Atlanta, GA",
    "West Palm Beach, FL - Chicago, IL",
    "West Palm Beach, FL - Cincinnati, OH",
    "West Palm Beach, FL - Cleveland, OH",
    "West Palm Beach, FL - Islip, NY",
    "West Palm Beach, FL - Philadelphia, PA",
    "West Palm Beach, FL - Trenton, NJ"
];

// Map city names to airport codes
const cityToCode = {
    "Aguadilla": "BQN",
    "Atlanta, GA": "ATL",
    "Austin, TX": "AUS",
    "Baltimore, MD": "BWI",
    "Bentonville/Fayetteville, AR": "XNA",
    "Boise, ID": "BOI",
    "Boston, MA": "BOS",
    "Bridgetown": "BGI",
    "Buffalo, NY": "BUF",
    "Burbank": "BUR",
    "Burlington, VT": "BTV",
    "Cabo San Lucas": "SJD",
    "Cancun, MX": "CUN",
    "Cedar Rapids, IA": "CID",
    "Charleston, SC": "CHS",
    "Charlotte, NC": "CLT",
    "Chicago, IL": "ORD",
    "Cincinnati, OH": "CVG",
    "Cleveland, OH": "CLE",
    "Columbus, OH": "CMH",
    "Corpus Christi": "CRP",
    "Dallas, TX": "DFW",
    "Denver, CO": "DEN",
    "Des Moines, IA": "DSM",
    "Detroit, MI": "DTW",
    "El Paso, TX": "ELP",
    "Fargo, ND": "FAR",
    "Fort Lauderdale, FL": "FLL",
    "Fort Myers, FL": "RSW",
    "Grand Rapids, MI": "GRR",
    "Green Bay, WI": "GRB",
    "Guatemala City": "GUA",
    "Harrisburg, PA": "MDT",
    "Hartford, CT": "BDL",
    "Houston, TX": "IAH",
    "Indianapolis, IN": "IND",
    "Islip, NY": "ISP",
    "Jacksonville, FL": "JAX",
    "Kansas City, MO": "MCI",
    "Knoxville, TN": "TYS",
    "Las Vegas, NV": "LAS",
    "Little Rock, AR": "LIT",
    "Los Angeles, CA": "LAX",
    "Madison, WI": "MSN",
    "Memphis, TN": "MEM",
    "Miami, FL": "MIA",
    "Milwaukee, WI": "MKE",
    "Minneapolis/St. Paul, MN": "MSP",
    "Missoula, MT": "MSO",
    "Montego Bay, Jamaica": "MBJ",
    "Myrtle Beach, SC": "MYR",
    "Nashville, TN": "BNA",
    "Nassau": "NAS",
    "New Orleans, LA": "MSY",
    "New York City, NY": "LGA",
    "Newark, NJ": "EWR",
    "Norfolk, VA": "ORF",
    "Oklahoma City, OK": "OKC",
    "Omaha, NE": "OMA",
    "Ontario/LA, CA": "ONT",
    "Orlando, FL": "MCO",
    "Oranjestad, Aruba": "AUA",
    "Palm Springs, CA": "PSP",
    "Pensacola, FL": "PNS",
    "Philadelphia, PA": "PHL",
    "Phoenix, AZ": "PHX",
    "Pittsburgh, PA": "PIT",
    "Ponce": "PSE",
    "Port-of-Spain": "POS",
    "Portland, ME": "PWM",
    "Portland, OR": "PDX",
    "Providenciales": "PLS",
    "Puerto Plata": "POP",
    "Puerto Vallarta, Mexico": "PVR",
    "Punta Cana, Dominican Republic": "PUJ",
    "Raleigh, NC": "RDU",
    "Reno, NV": "RNO",
    "Richmond": "RIC",
    "Sacramento, CA": "SMF",
    "Saint Croix": "STX",
    "Salt Lake City, UT": "SLC",
    "San Antonio, TX": "SAT",
    "San Diego, CA": "SAN",
    "San Francisco, CA": "SFO",
    "San Jose, CA": "SJC",
    "San Jose, CR": "SJO",
    "San Juan, PR": "SJU",
    "San Pedro Sula": "SAP",
    "San Salvador": "SAL",
    "Santa Ana, CA": "SNA",
    "Santiago de los Caballeros": "STI",
    "Santo Domingo": "SDQ",
    "Sarasota, FL": "SRQ",
    "Savannah, GA": "SAV",
    "Seattle, WA": "SEA",
    "Sioux Falls, SD": "FSD",
    "Spokane, WA": "GEG",
    "St. John's, Antigua": "ANU",
    "St. Louis, MO": "STL",
    "St. Maarten": "SXM",
    "St. Thomas": "STT",
    "Syracuse, NY": "SYR",
    "Tampa, FL": "TPA",
    "Trenton, NJ": "TTN",
    "Tucson, AZ": "TUS",
    "Tulsa, OK": "TUL",
    "Vail": "EGE",
    "Washington, D.C.": "DCA",
    "West Palm Beach, FL": "PBI"
};

function seedRoutes() {
    console.log('Seeding routes database...');

    let successCount = 0;
    let failCount = 0;

    frontierRoutes.forEach(route => {
        const parts = route.split(' - ');
        if (parts.length !== 2) {
            console.log(`Skipping malformed route: ${route}`);
            failCount++;
            return;
        }

        const originCity = parts[0].trim();
        const destCity = parts[1].trim();

        const originCode = cityToCode[originCity];
        const destCode = cityToCode[destCity];

        if (originCode && destCode) {
            try {
                upsertRoute(originCode, destCode);
                successCount++;
            } catch (error) {
                console.error(`Error inserting route ${originCode} -> ${destCode}:`, error.message);
                failCount++;
            }
        } else {
            if (!originCode) console.log(`Unknown origin city: ${originCity}`);
            if (!destCode) console.log(`Unknown destination city: ${destCity}`);
            failCount++;
        }
    });

    console.log(`\nSeeding complete!`);
    console.log(`✅ Successfully added: ${successCount} routes`);
    console.log(`❌ Failed: ${failCount} routes`);

    return successCount;
}

// Run if called directly
if (require.main === module) {
    seedRoutes();
    console.log('\nRoutes have been seeded to the database.');
}

module.exports = { seedRoutes, cityToCode };
